# ************************************************************************************************
# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).
# Use the maker portal to create and edit your Power Apps.
# 
# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907
# 
# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623
# ************************************************************************************************
Screens:
  Profile - Settings:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
    Children:
      - Background Color_3:
          Control: Rectangle@2.3.0
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            BorderStyle: =BorderStyle.None
            Fill: =fxTheme.Header.BGColor
            Height: =111
            Width: =Parent.Width
      - Back Button_4:
          Control: Classic/Icon@2.5.0
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =fxTheme.Header.TextColor
            Height: =fxTheme.Header.IconSize
            Icon: =Icon.ArrowLeft
            OnSelect: =Back( ScreenTransition.Cover)
            Width: =fxTheme.Header.IconSize
            X: =30
            Y: =30
      - Label2_2:
          Control: Label@2.5.1
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =fxTheme.Header.TextColor
            Font: =Font.Lato
            Size: =26
            Text: ="Settings"
            Width: =149
            X: |
              =(Parent.Width - Self.Width) / 2
            Y: =20
      - Label16:
          Control: Label@2.5.1
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Font: =Font.Lato
            Text: ="Notifications"
            Width: =233
            X: =30
            Y: =146
      - Toggle1:
          Control: Classic/Toggle@2.1.0
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Font: =Font.'Open Sans'
            Height: =27
            TrueFill: =RGBA(56, 96, 178, 1)
            Width: =114
            X: =476
            Y: =167
